steps:
- id: 'tf plan'
  name: hashicorp/terraform:latest
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "branch $BRANCH_NAME"
      cd terraform
      echo "run init"
      terraform init
      echo "run validate"
      terraform validate
      echo "run plan"
      terraform plan -out terraform.plan
options:
  logging: CLOUD_LOGGING_ONLY
      