steps:
- id: 'tf plan'
  name: 'hashincorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "branch $BRANCH_NAME"
      cd terraform
      echo "run init"
      terraform init
      echo "run validate"
      terraform validate
      echo "run plan"
      terraform plan -out terraform.plan
      